## How many kubescale pods should run in deployment
replicaCount: 1

rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if rbac.create is true
  serviceAccountName: kubescale
  extraRules: []
   # - apiGroups:
   #     - argoproj.io
   #   resources:
   #     - rollouts
   #   verbs:
   #     - get
   #     - watch
   #     - list
   #     - update
   #     - patch

image:
  repository: ghcr.io/cicd-toolkit/cicd-toolkit/kubescale
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  pullPolicy: IfNotPresent
  args: []



resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 150m
    memory: 256Mi

podSecurityContext:
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []

containerSecurityContext:
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

extraLabels: {}


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
priorityClassName: ""
