{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{ include "kubescale.labels" . | nindent 4 }}
  name: {{ template "kubescale.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ template "kubescale.fullname" . }}"
subjects:
- kind: ServiceAccount
  name: "{{ template "kubescale.fullname" . }}"
  namespace: {{ .Release.Namespace }}
{{- end -}}
