
name: kuttl
on:
  pull_request:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker
        run: |
            make docker-build

      - name: run
        run: |
          echo "### Add homebrew to path as described in https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#notes"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          echo "### Install kuttl via brew"
          brew tap kudobuilder/tap
          brew install kuttl-cli

          echo "### Let's try to use kuttl"
          kubectl kuttl --version

          echo "### Run kuttl tests"
          kubectl kuttl test

